spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: "jdbc:mysql://localhost:3306/dream?useSSL=false&allowPublicKeyRetrieval=true"
      username: root
      password: dream
      auto-commit: false     # AOP로 트랜잭션을 제어하기 때문에 false로 사용 (default: true)
      connection-timeout: 30000   # 커넥션 타임 아웃 (30s)
      idle-timeout: 600000   # pool 미사용 커넥션 유지 시간 (10m)
      max-lifetime: 1800000  # pool 에서 미사용 커넥션 최대 수명 시간 (30m)
      minimum-idle: 1        # 최소 커넥션 유지 개수 (default: same as maximumPoolSize)
      maximum-pool-size: 10  # pool에 유지시킬 수 있는 최대 커넥션 수
      pool-name: bong-hikari-pool