spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
<<<<<<< HEAD
=======
    # org.hibernate.type: trace - 이 값을 사용하면 바인딩 되는 파라미터 확인 가능
>>>>>>> f147e4235663f3bbb4ff3d4b4581744d991208ac
